annotations: ''
appName: portainer-proxy
appRole: proxy
destNamespace: portainer-proxy
destProject: "proxy"
destServer: https://kubernetes.default.svc
exclude: ""
include: ""
labels: ""
srcPath: apps/prod/portainer-proxy
srcRepoURL: https://github.com/JacekZubielik/dev-k3s-lab-autopilot.git
srcTargetRevision: ""
syncPriority: stage_1
syncWave: 0
userGivenName: portainer-proxy
