---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# metadata:
#   annotations:
#     argocd.argoproj.io/compare-options: IgnoreExtraneous
#   labels:
#     syncPriority: stage4

resources:
# - https://raw.githubusercontent.com/longhorn/longhorn/master/chart/templates/crds.yaml
- resources/crds.yaml