annotations: 'argocd.argoproj.io/compare-options: IgnoreExtraneous'
appName: crds-csi-snapshotter
appRole: csi
destNamespace: ""
destServer: https://kubernetes.default.svc
exclude: ""
include: ""
labels: ""
srcPath: apps/crds/crds-csi-external-snapshotter
srcRepoURL: https://github.com/JacekZubielik/dev-k3s-lab-autopilot.git
srcTargetRevision: ""
syncPriority: stage2
syncWave: -1
userGivenName: crds-csi-snapshotter
