annotations: ''
appName: kube-prometheus-stack
appRole: monitoring
destNamespace: monitoring
destProject: "infra"
destServer: https://kubernetes.default.svc
exclude: ""
include: ""
labels: ""
srcPath: apps/infra/kube-prometheus-stack
srcRepoURL: https://github.com/JacekZubielik/dev-k3s-lab-autopilot.git
srcTargetRevision: ""
syncPriority: stage_4
syncWave: 0
userGivenName: kube-prometheus-stack
