---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jellyfin
  name: jellyfin-svc
  namespace: jellyfin
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.40.186
  # sessionAffinity: ClientIP
  ports:
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  - name: http
    port: 8096
    protocol: TCP
    targetPort: 8096
  - name: web-udp
    port: 8096
    protocol: UDP
    targetPort: 8096
  - name: dlna-udp
    port: 1900
    protocol: UDP
    targetPort: 1900
  - name: discovery-udp
    port: 7359
    protocol: UDP
    targetPort: 7359
  selector:
    app: jellyfin
---
apiVersion: v1
kind: Endpoints
metadata:
  name: jellyfin-svc
  namespace: jellyfin
subsets:
- addresses:
  - ip: 192.168.40.186
  ports:
  - name: dns-tcp
    port: 53
  - name: http
    port: 8096
  - name: web-udp
    port: 8096
    protocol: UDP
  - name: dlna-udp
    port: 1900
    protocol: UDP
  - name: discovery-udp
    port: 7359
    protocol: UDP
