annotations: ''
appName: monitoring
appRole: applicationset
destNamespace: ""
destServer: https://kubernetes.default.svc
exclude: ""
include: ""
labels: ""
srcPath: apps/monitoring
srcRepoURL: https://github.com/JacekZubielik/dev-k3s-lab-autopilot.git
srcTargetRevision: ""
syncPriority: stage3
syncWave: -1
userGivenName: monitoring
