annotations: ''
appName: media
appRole: applicationset
destNamespace: ""
destServer: https://kubernetes.default.svc
exclude: ""
include: ""
labels: ""
srcPath: apps/media
srcRepoURL: https://github.com/JacekZubielik/dev-k3s-lab-autopilot.git
srcTargetRevision: ""
syncPriority: stage5
syncWave: "-1"
userGivenName: media
