annotations: ''
appName: uptime-kuma
appRole: monitoring
destNamespace: uptime-kuma
destProject: "infra"
destServer: https://kubernetes.default.svc
exclude: ""
include: ""
labels: ""
srcPath: apps/infra/uptime-kuma
srcRepoURL: https://github.com/JacekZubielik/dev-k3s-lab-autopilot.git
srcTargetRevision: ""
syncPriority: stage_5
syncWave: 2
userGivenName: uptime-kuma
