---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Delete=true,Prune=true

resources:
- resources/ns.yaml
- resources/pv.yaml
- resources/pvc.yaml
- resources/volume.yaml
# - resources/volume.backingimage.yaml
- velero/job.restore.pvc.yaml


# - resources/volume.snapshot.backingimage.yaml # longhorn backup test
# - resources/volume.backingimage.yaml # longhorn backup test
# - resources/volume.snapshot.content.yaml
# - velero/backup.backingimage.yaml
# - velero/backup.yaml # velero backup test
# - velero/restore.yaml
# - velero/schedule.yaml # velero backup test

# generators:
# - ksops-generator.yaml

configMapGenerator:
- name: kuma-config
  literals:
  - UPTIME_KUMA_PORT=3001
- name: kuma-tz
  literals:
  - TZ=CET

generatorOptions:
  disableNameSuffixHash: true
  labels:
    component: uptime-kuma

helmCharts:
- name: uptime-kuma
  repo: https://jacekzubielik.github.io/jz-helm-charts
  version: 0.0.4
  includeCRDs: false
  namespace: uptime-kuma
  releaseName: uptime-kuma
  valuesFile: values.yaml
