---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: storage
  namespace: argocd
  labels:
    dev-k3s: storage
    syncPriority: stage2

spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/JacekZubielik/dev-k3s-lab-autopilot.git
      revision: HEAD
      directories:
        - path: apps/storage/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: storage
      source:
        repoURL: https://github.com/JacekZubielik/dev-k3s-lab-autopilot.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: false
          prune: true

  strategy:
    type: RollingSync
    rollingSync:
      steps:
      - matchExpressions:
        - key: syncPriority
          operator: In
          values:
          - stage1 #
        maxUpdate: 100%
      - matchExpressions:
        - key: syncPriority
          operator: In
          values:
          - stage2 #
        maxUpdate: 100%
      - matchExpressions:
        - key: syncPriority
          operator: In
          values:
          - stage3 #
        maxUpdate: 100%
      - matchExpressions:
        - key: syncPriority
          operator: In
          values:
          - stage4 #
        maxUpdate: 100%
