---
apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  finalizers:
  - longhorn.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    longhornvolume: pvc-esphome-data
    recurring-job-group.longhorn.io/group1: enabled
    recurring-job.longhorn.io/24-hour-snapshots: enabled
    recurring-job.longhorn.io/48-hour-backups: enabled
  name: pvc-esphome-data
  namespace: longhorn-system
spec:
  # backingImage: pvc-esphome-data
  dataLocality: best-effort
  diskSelector:
  - data
  # - fast
  # fromBackup: s3://k3s-longhorn-backup@us-east-1/?backup=backup-433d96f29ba347c1&volume=pvc-esphome-data
  frontend: blockdev
  # migratable: false
  nodeSelector:
  - fast
  # - storage
  numberOfReplicas: 1
  size: '10737418240'
  snapshotMaxCount: 20
