---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: portainer-proxy
  name: portainer-proxy
  namespace: portainer-proxy
spec:
  externalName: 192.168.40.3
  type: ExternalName
  ports:
  - name: websecure
    port: 9443
    targetPort: 9443
  selector:
    app.kubernetes.io/instance: portainer-proxy
    task: portainer-proxy
---
# Endpoint for the headless service without selector
apiVersion: v1
kind: Endpoints
metadata:
  name: portainer-proxy
  namespace: portainer-proxy
subsets:
- addresses:
  - ip: 192.168.40.3
  ports:
  - name: websecure
    port: 9443
