---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous

resources:
- resources/cm.yaml
- resources/pv.yaml
- resources/pvc.yaml
# - resources/volume.snapshot.yaml
- resources/volume.yaml
# - resources/backing-image.yaml
# - resources/backup.backing-image.yaml

generators:
- ksops-generator.yaml

generatorOptions:
  disableNameSuffixHash: true

helmCharts:
- name: zigbee2mqtt
  version: 0.0.10
  repo: https://jacekzubielik.github.io/jz-helm-charts
  includeCRDs: false
  namespace: zigbee2mqtt
  releaseName: zigbee2mqtt
  valuesFile: values.yaml
