---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Delete=true,Prune=true

resources:
- resources/cm.yaml
- resources/pv.yaml
- resources/pvc.yaml
- resources/volume.yaml

generators:
- ksops-generator.yaml

# configMapGenerator:
# - name: zigbee2mqtt-tz
#   literals:
#   - TZ=CET


generatorOptions:
  disableNameSuffixHash: true
  labels:
    component: zigbee2mqtt

helmCharts:
- name: zigbee2mqtt
  version: 0.0.10
  repo: https://jacekzubielik.github.io/jz-helm-charts
  includeCRDs: false
  namespace: zigbee2mqtt
  releaseName: zigbee2mqtt
  valuesFile: values.yaml
