---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Delete=true,Prune=true

resources:
- resources/ns.yaml
- resources/pv.yaml
- resources/pvc.yaml
- resources/service.yaml
- resources/volume.yaml
- velero/schedule.yaml
# - resources/servicemonitor.yaml

# generators:
# - ksops-generator.yaml

configMapGenerator:
- name: ha-tz
  literals:
  - TZ=CET

generatorOptions:
  disableNameSuffixHash: true
  labels:
    component: home-assistant

helmCharts:
- name: home-assistant
  repo: https://jacekzubielik.github.io/jz-helm-charts
  version: 0.0.11
  includeCRDs: false
  namespace: home-assistant
  releaseName: home-assistant
  valuesFile: values.yaml
