annotations: ''
appName: argocd-proxy
appRole: proxy
destNamespace: argocd
destProject: "proxy"
destServer: https://kubernetes.default.svc
exclude: ""
include: ""
labels: ""
srcPath: apps/prod/argocd-proxy
srcRepoURL: https://github.com/JacekZubielik/dev-k3s-lab-autopilot.git
srcTargetRevision: ""
syncPriority: stage_1
syncWave: 0
userGivenName: argocd-proxy
