annotations: ''
appName: mosquitto
appRole: iot
destNamespace: mosquitto
destProject: dev
destServer: https://kubernetes.default.svc
exclude: ""
include: ""
labels: ""
srcPath: apps/dev/mosquitto
srcRepoURL: https://github.com/JacekZubielik/dev-k3s-lab-autopilot.git
srcTargetRevision: "mosquitto"
syncPriority: stage_1
syncWave: 0
userGivenName: mosquitto
