annotations: ''
appName: prod-bootstrap
appRole: infra
destNamespace: ""
destProject: "default"
destServer: https://kubernetes.default.svc
exclude: ""
include: ""
labels: ""
srcPath: apps/infra/prod
srcRepoURL: https://github.com/JacekZubielik/dev-k3s-lab-autopilot.git
srcTargetRevision: ""
syncPriority: stage6
syncWave: 0
userGivenName: prod-bootstrap
