annotations: 'argocd.argoproj.io/compare-options: IgnoreExtraneous'
appName: crds-prometheus-stack
appRole: prometheus-stack
destNamespace: ""
destServer: https://kubernetes.default.svc
exclude: ""
include: ""
labels: ""
srcPath: apps/crds/crds-prometheus-stack
srcRepoURL: https://github.com/JacekZubielik/dev-k3s-lab-autopilot.git
srcTargetRevision: ""
syncPriority: stage3
syncWave: -1
userGivenName: crds-prometheus-stack
