annotations: ''
appName: csi-external-snapshotter
appRole: infra
destNamespace: kube-system
destProject: "infra"
destServer: https://kubernetes.default.svc
exclude: ""
include: ""
labels: ""
srcPath: apps/infra/csi-external-snapshotter
srcRepoURL: https://github.com/JacekZubielik/dev-k3s-lab-autopilot.git
srcTargetRevision: ""
syncPriority: stage4
syncWave: 0
userGivenName: csi-external-snapshotter
