---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mktxp

# metadata:
#   annotations:
#     argocd.argoproj.io/compare-options: IgnoreExtraneous

resources:
- resources/deployment.yaml
- resources/service.yaml
- resources/servicemonitor.yaml

generators:
- ksops-generator.yaml

configMapGenerator:
- name: mktxp-exporter-tz
  literals:
  - TZ=CET

generatorOptions:
  disableNameSuffixHash: true
