annotations: ''
appName: crds-prometheus-stack
appRole: prometheus-stack
destNamespace: ""
destProject: "crds"
destServer: https://kubernetes.default.svc
exclude: ""
include: ""
labels: ""
srcPath: apps/infra/crds-prometheus-stack
srcRepoURL: https://github.com/JacekZubielik/dev-k3s-lab-autopilot.git
srcTargetRevision: ""
syncPriority: stage_crds
syncWave: 2
userGivenName: crds-prometheus-stack
