annotations: ''
appName: syncthing
appRole: storage
destNamespace: syncthing
destProject: "storage"
destServer: https://kubernetes.default.svc
exclude: ""
include: ""
labels: ""
srcPath: apps/prod/syncthing
srcRepoURL: https://github.com/JacekZubielik/dev-k3s-lab-autopilot.git
srcTargetRevision: ""
syncPriority: stage_2
syncWave: 0
userGivenName: syncthing
