annotations: ''
appName: syncthing
appRole: media
destNamespace: syncthing
destProject: "media"
destServer: https://kubernetes.default.svc
exclude: ""
include: ""
labels: ""
srcPath: apps/prod/syncthing
srcRepoURL: https://github.com/JacekZubielik/dev-k3s-lab-autopilot.git
srcTargetRevision: ""
syncPriority: stage1
syncWave: 1
userGivenName: syncthing
