annotations: ''
appName: traefik
appRole: infra
destNamespace: traefik
destServer: https://kubernetes.default.svc
exclude: ""
include: ""
labels: ""
srcPath: apps/infra/traefik
srcRepoURL: https://github.com/JacekZubielik/dev-k3s-lab-autopilot.git
srcTargetRevision: ""
syncPriority: stage2
syncWave: 0
userGivenName: traefik
