annotations: ''
appName: trade
appRole: applicationset
destNamespace: ""
destServer: https://kubernetes.default.svc
exclude: ""
include: ""
labels: ""
srcPath: apps/trade
srcRepoURL: https://github.com/JacekZubielik/dev-k3s-lab-autopilot.git
srcTargetRevision: ""
syncPriority: stage6
syncWave: "-1"
userGivenName: trade
