---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Delete=true,Prune=true

resources:
- resources/deployment.yaml
- resources/ns.yaml
- resources/pv.yaml
- resources/pvc.yaml
- resources/service.yaml
- resources/volume.yaml

generators:
- ksops-generator.yaml

configMapGenerator:
- name: freqtrade-tz
  literals:
  - TZ=CET
- name: freqtrade-config
  files:
  - resources/freqtrade-config.cm.yaml

generatorOptions:
  disableNameSuffixHash: true
  labels:
    component: freqtrade

# patches:
# - target:
#     kind: CustomResourceDefinition
#   patch: |-
#     - op: remove
#       path: /metadata/labels/app.kubernetes.io~1instance
