annotations: 'argocd.argoproj.io/compare-options: IgnoreExtraneous'
appName: crds-cert-manager
appRole: cert-manager
destNamespace: ""
destServer: https://kubernetes.default.svc
exclude: ""
include: ""
labels: ""
srcPath: apps/crds/crds-cert-manager
srcRepoURL: https://github.com/JacekZubielik/dev-k3s-lab-autopilot.git
srcTargetRevision: ""
syncPriority: stage1
syncWave: 0
userGivenName: crds-cert-manager
