---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: mosquitto
spec:
  type: LoadBalancer
  loadBalancerIP: "192.168.40.189"
  externalTrafficPolicy: Local
  ports:
  - name: mqttport
    port: 1883
    targetPort: mqttport
    protocol: TCP
    nodePort: 30088
  # - name: mqttsPort
  #   port: 8883
  #   targetPort: mqttsPort
  #   protocol: TCP
  #   nodePort: 30089

  selector:
    app.kubernetes.io/name: mosquitto
