---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  labels:
    dev-k3s: dev
  name: dev
  namespace: argocd

spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/JacekZubielik/dev-k3s-lab-autopilot.git
      requeueAfterSeconds: 10
      revision: ""
      files:
      - path: apps/dev/**/config.yaml
      template:
        metadata:
          labels:
            app.kubernetes.io/managed-by: argocd-autopilot
        spec:
          destination: {}
          project: ""
          source:
            repoURL: ""

  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: '{{ .syncWave }}'
      labels:
        app.kubernetes.io/managed-by: argocd-autopilot
        app.kubernetes.io/name: '{{ .appName }}'
        application-role: '{{ .appRole }}'
        syncPriority: '{{ .syncPriority }}'
      name: dev-{{ .userGivenName }}
      namespace: argocd

    spec:
      project: '{{ .destProject }}'
      source:
        path: '{{ .srcPath }}'
        repoURL: '{{ .srcRepoURL }}'
        targetRevision: '{{ .srcTargetRevision }}'
      destination:
        namespace: '{{ .destNamespace }}'
        server: '{{ .destServer }}'

      ignoreDifferences:
      - group: argoproj.io
        kind: Application
        jsonPointers:
        - /status
      - group: argoproj.io
        kind: Application
        jsonPointers:
        - /operation
      - group: "apps"
        kind: "Deployment"
        jsonPointers:
        - /spec/template/metadata/annotations
        - /spec/template/metadata/labels
      - group: "apps"
        kind: "StatefulSet"
        jsonPointers:
        - /spec/template/metadata/annotations
        - /spec/template/metadata/labels
      # - kind: PersistentVolume
      #   jsonPointers:
      #   - /spec/claimRef/resourceVersion
      #   - /spec/claimRef/uid
      #   - /status/lastPhaseTransitionTime

      syncPolicy:
        automated:
          selfHeal: false
          prune: true
        syncOptions:
        - ApplyOutOfSyncOnly=true
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - RespectIgnoreDifferences=true
        - ServerSideApply=true
        - SkipDryRunOnMissingResource=true

  strategy:
    type: RollingSync
    rollingSync:
      steps:
      - matchExpressions:
        - key: syncPriority
          operator: In
          values:
          - stage1
        # maxUpdate: 100%
      - matchExpressions:
        - key: syncPriority
          operator: In
          values:
          - stage2
        # maxUpdate: 100%
      - matchExpressions:
        - key: syncPriority
          operator: In
          values:
          - stage3
        # maxUpdate: 0%

