annotations: ''
appName: lms
appRole: media
destNamespace: lms
destProject: "media"
destServer: https://kubernetes.default.svc
exclude: ""
include: ""
labels: ""
srcPath: apps/prod/lms
srcRepoURL: https://github.com/JacekZubielik/dev-k3s-lab-autopilot.git
srcTargetRevision: ""
syncPriority: stage2
syncWave: 0
userGivenName: lms
