annotations: 'argocd.argoproj.io/compare-options: IgnoreExtraneous'
appName: crds-traefik
appRole: traefik
destNamespace: ""
destServer: https://kubernetes.default.svc
exclude: ""
include: ""
labels: ""
srcPath: apps/crds/crds-traefik
srcRepoURL: https://github.com/JacekZubielik/dev-k3s-lab-autopilot.git
srcTargetRevision: ""
syncPriority: stage4
syncWave: 0
userGivenName: crds-traefik
