---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
  # labels:
  #   dev-k3s: apps
  #   syncPriority: stage1

spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/JacekZubielik/dev-k3s-lab-autopilot.git
      revision: HEAD
      directories:
        - path: apps/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: infrastructure
      source:

        repoURL: https://github.com/JacekZubielik/dev-k3s-lab-autopilot.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: true
          prune: true

  strategy:
    type: RollingSync
    rollingSync:
      steps:
      - matchExpressions:
        - key: syncPriority
          operator: In
          values:
          - stage1 # crds
        maxUpdate: 0%
      - matchExpressions:
        - key: syncPriority
          operator: In
          values:
          - stage2 # storage
        maxUpdate: 100%
      - matchExpressions:
        - key: syncPriority
          operator: In
          values:
          - stage3 # infra
        maxUpdate: 100%
      - matchExpressions:
        - key: syncPriority
          operator: In
          values:
          - stage4 # monitoring
        maxUpdate: 100%
