annotations: ""
appName: minio
appRole: storage
destNamespace: minio
destServer: https://kubernetes.default.svc
exclude: ""
include: ""
labels: ""
srcPath: apps/storage/minio
srcRepoURL: https://github.com/JacekZubielik/dev-k3s-lab-autopilot.git
srcTargetRevision: ""
syncPriority: stage1
syncWave: 0
userGivenName: minio
