annotations: ''
appName: external-dns
appRole: infra
destNamespace: cert-manager
destServer: https://kubernetes.default.svc
exclude: ""
include: ""
labels: ""
srcPath: apps/infra/external-dns
srcRepoURL: https://github.com/JacekZubielik/dev-k3s-lab-autopilot.git
srcTargetRevision: ""
syncPriority: stage5
syncWave: 0
userGivenName: external-dns
