annotations: ''
appName: longhorn
appRole: infra
destNamespace: longhorn-system
destProject: "infra"
destServer: https://kubernetes.default.svc
exclude: ""
include: ""
labels: ""
srcPath: apps/infra/longhorn
srcRepoURL: https://github.com/JacekZubielik/dev-k3s-lab-autopilot.git
srcTargetRevision: ""
syncPriority: stage_3
syncWave: 0
userGivenName: longhorn
