annotations: ''
appName: argocd-proxy
appRole: infra
destNamespace: traefik
destProject: "infra"
destServer: https://kubernetes.default.svc
exclude: ""
include: ""
labels: ""
srcPath: apps/infra/argocd-proxy
srcRepoURL: https://github.com/JacekZubielik/dev-k3s-lab-autopilot.git
srcTargetRevision: ""
syncPriority: stage_6
syncWave: 0
userGivenName: argocd-proxy
