annotations: ''
appName: intel-nfd
appRole: infra
destNamespace: intel-nfd
destProject: "dev"
destServer: https://kubernetes.default.svc
exclude: ""
include: ""
labels: ""
srcPath: apps/dev/intel-nfd
srcRepoURL: https://github.com/JacekZubielik/dev-k3s-lab-autopilot.git
srcTargetRevision: ""
syncPriority: stage_1
syncWave: 1
userGivenName: intel-nfd
