---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: minio-proxy
  name: minio-proxy
  namespace: traefik
spec:
  externalName: 192.168.40.3
  type: ExternalName
  ports:
  - name: minio-proxy
    port: 9001
    targetPort: 9001
  - name: minio-api
    port: 9002
    targetPort: 9002
  selector:
    app.kubernetes.io/instance: minio-proxy
    task: minio-proxy
