---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio-proxy
  name: minio-proxy
  namespace: minio
spec:
  externalName: 192.168.40.3
  type: ExternalName
  ports:
  - name: minio-proxy
    port: 9001
    targetPort: 9001
  selector:
    app: minio-proxy
    task: minio-proxy
---
# Endpoint for the headless service without selector
apiVersion: v1
kind: Endpoints
metadata:
  name: minio-proxy
  namespace: minio
subsets:
- addresses:
  - ip: 192.168.40.3
  ports:
  - name: minio-proxy
    port: 9001

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio-api
  name: minio-api
  namespace: minio
spec:
  externalName: 192.168.40.3
  type: ExternalName
  ports:
  - name: minio-api
    port: 9002
    targetPort: 9002
  selector:
    app: minio-api
    task: minio-api
---
# Endpoint for the headless service without selector
apiVersion: v1
kind: Endpoints
metadata:
  name: minio-api
  namespace: minio
subsets:
- addresses:
  - ip: 192.168.40.3
  ports:
  - name: minio-api
    port: 9002




# ---
# # Headless service for Minio metrics. No Selector
# apiVersion: v1
# kind: Service
# metadata:
#   name: minio-metrics-service
#   labels:
#     app.kubernetes.io/name: minio
#   namespace: kube-system
# spec:
#   # clusterIP: None
#   ports:
#   - name: http-metrics
#     port: 9002
#     protocol: TCP
#     targetPort: 9002
#   type:  ClusterIP # LoadBalancer
# ---
# # Endpoint for the headless service without selector
# apiVersion: v1
# kind: Endpoints
# metadata:
#   name: minio-metrics-service
#   namespace: kube-system
# subsets:
# - addresses:
#   - ip: 192.168.40.3
#   ports:
#   - name: http-metrics
#     port: 9002

