annotations: ''
appName: kube-prometheus-stack
appRole: monitoring
destNamespace: monitoring
destServer: https://kubernetes.default.svc
exclude: ""
include: ""
labels: ""
srcPath: apps/monitoring/kube-prometheus-stack
srcRepoURL: https://github.com/JacekZubielik/dev-k3s-lab-autopilot.git
srcTargetRevision: ""
syncPriority: stage2
syncWave: 0
userGivenName: kube-prometheus-stack
