annotations: ''
appName: authentik
appRole: infra
destNamespace: authentik
destProject: "crds"
destServer: https://kubernetes.default.svc
exclude: ""
include: ""
labels: ""
srcPath: apps/infra/authentik
srcRepoURL: https://github.com/JacekZubielik/dev-k3s-lab-autopilot.git
srcTargetRevision: ""
syncPriority: stage7
syncWave: 0
userGivenName: authentik
